apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: k8s
    image: nginx
    ports:
    - containerPort: 80
  - name: monitor
    image: afakharany/watcher
    ports:
    - containerPort: 8080
